site_name: EngramAI Lite
site_description: A memory graph storage system for AI agents
site_author: EngramAI Team
repo_url: https://github.com/nkkko/engram-lite
repo_name: nkkko/engram-lite

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quickstart: getting-started/quickstart.md
  - Usage:
    - CLI: usage/cli.md
    - TUI: usage/tui.md
    - API: usage/api.md
  - Design:
    - Data Model: design/data-model.md
    - Storage: design/storage.md
    - Graph Engine: design/graph-engine.md
    - Indexing: design/indexing.md
  - About:
    - Roadmap: about/roadmap.md
    - Contributing: about/contributing.md
    - License: about/license.md

plugins:
  - search